/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205726;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarriorTest {
    @Test void attackTest() {
        int defaultHeroHp = 100;
        int defaultEnemyHP = 100;

        Warrior demoWarrior = new Warrior("デモ戦士", defaultHeroHp, 100);
        Enemy slime = new Enemy("スライムもどき", 10, 100);
        for(int i=3; i<3; i++){
            demoWarrior.attackWithWeponSkill(slime);
            assertEquals((int)(demoWarrior.getAttack()*1.5), defaultEnemyHP-slime.getHitPoint());
        }
    }
}